### PR TITLE
April 2018 Official Run

### PR DESCRIPTION
**Pull request by clhorner**
April 2018 official run and results.

### CODE REVIEW

**Comment by cfelletter** [comment]
@clhorner let's add the 24MS_Data.xlsx if we are going to distribute this to the users.

**Comment by stighi** [comment]
We have not included the 24MS_Data.xlsx file with the MTOM package in the past. It shouldn't be necessary to include it since the MTOM model file comes already initialized for the April run. The users would only need that file to initialize the model.

**Comment by cfelletter** [comment]
@clhorner Got it. Do we want stakeholders to be able to generate EnsembleForecasts.xlsx and then run the model?  I can generate EnsembleForecasts but to do so prior to hitting 'Done'  I have to enter my HDB login information. Perhaps we could consider changing this so that the sheet to could be generated without connecting to HDB since the data is already there in the CBRFC sheet?

**Comment by clhorner** [comment]
We typically provide the pass through spreadsheet since those without access to HBD will not be able to generate it themselves. I'm not entirely sure why that isn't in the April files I uploaded. I'll try to push those files again and create a new pull request so that we have all the necessary files in our master branch. 

As for changing how the Ensemble Forecast spreadsheets are set up, I will defer to @stighi or maybe that's a topic for discussion at our next coordination call.

**Comment by cfelletter** [comment]
@clhorner everything looks good and my run reproduced your results. When you make the final commit of adding the changing log be sure to use a tag like "closes #11" or similar and then this issue will be closed when we merge into the master. For more info on using keywords in commits: 
https://help.github.com/articles/closing-issues-using-keywords/
Going forward we can keep issues open until merging them to the master and just use commit and keywords to close them.

**Comment by rabutler-usbr** [comment]
@clhorner Shouldn't this PR still be open? It looks like it was closed but not merged into the master, unless I'm missing something.

**Comment by rabutler-usbr** [comment]
@clhorner Also, does this MTOM model file include the MWD ICS output, since you had to re-run that for Jessie.

**Comment by rabutler-usbr** [comment]
@clhorner n/m I see that you need to issue another PR? If all you need to do is add an additional file to the PR, you can change the dev branch and it *should* automatically update your existing PR

**Comment by clhorner** [comment]
@rabutler-usbr sorry for the confusion. I had to update a few things (including the MTOMtoCRSS outputs) and I realized that I need to wait until the April Model Assumptions Updates document is finished to have the completed April package ready to merge into the master branch. I'm still waiting on review and approval of the document. I figured I would close the pull request until then so that we don't merge the branches prematurely. I also didn't realize the pull request would update as a I updated the dev branch, thanks for clarifying.

**Comment by rabutler-usbr** [comment]
@clhorner no worries at all. Yep, I agree it does make sense to keep it closed, until you're ready for it to be merged.

**Comment by cfelletter** [comment]
I also believe reopening and merging is the way to go once we have the final files in.

**Pull request closed without merging**
